name: MichaelColasardo
favicon: null
layout_spectrum: 0.9264879112597555
typography_spectrum: 0.6936221218202263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7541850707493722
  lightness: 0.3411276610568166
  saturation: 0.5963341577444226
  rhythmicContrast: 0.8100960666779429
purpose: []
