name: MichaelColasardo
favicon: null
layout_spectrum: 0.95989
typography_spectrum: 0.41071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#90dee6'
    - '#f66335'
    - '#fed653'
    - '#2cc3d3'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
